### ISSUE TITLE
Increase version number for installation on Blackboard SaaS

### ISSUE THREAD

**Issue by jbaxe2** [celtic-project/bb-basiclti#10]
Hello,
I attempted to have Blackboard update the building block on a SaaS.  However, they are claiming that they cannot perform the upgrade, due to the version number being the same:

> I have been researching on this case to find a way to update this Building Block, however, and unfortunately, after checking with our Provisioning team, since the upgrades on our side are placed taking the version number provided by the developer, when we try to make this updates on our system, nothing happens, due to the version number being the same. We would need to upgrade to a version of this Building Block with a different or higher version number, so that the update of the same takes effect.

Can the *.war file be rebuilt with an incremented version?

Thanks.

**Comment by spvickers** [comment]
I have resisted updating the version number because of issues with links to course tools being deleted by Learn when this changes.  See the note on the version history section of the documentation page: "NB Verson number not changed - check the settings page to confirm the release date."  I am not aware of any issues with uploading this new war file to replace the older versions, but please let me have more details if this is really not possible.
